name: Dependency-Check

on:
  push:
    branches:
      - main  # замените на основную ветку вашего проекта
  pull_request:
    branches:
      - main  # замените на основную ветку вашего проекта

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Download and run OWASP Dependency-Check
      run: |
        curl -L -o dependency-check.zip https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.5-release.zip
        unzip dependency-check.zip
        ./dependency-check/bin/dependency-check.sh --project "Fast api.py" --scan . --format "HTML" --out ./dependency-check-report

    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./dependency-check-report.html
