name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Semgrep security scan
      run: docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep --config /src/rules.yaml -o /srcsemgrep-report.html

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep-report.html

  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Download and run OWASP Dependency-Check
      run: |
        wget -O dependency-check.zip https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.1.5-release.zip

        if [ ! -f dependency-check.zip ]; then
          echo "Failed to download dependency-check.zip"
          exit 1
        fi
        
        unzip dependency-check.zip

        ./dependency-check/bin/dependency-check.sh --project "My Python Project" --scan . --format "HTML" --out ./dependency-check-report

    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: ./dependency-check-report.html
